### PR TITLE
Remove unknown data from footnote and add to the README when downloading datasets

### LINKED ISSUE #514: Move extra-long footnotes to the README.txt
In some cases, we want to proactively explain possible incongruencies between views of the data; for example, when some data (e.g., race/ethnicity) is not reported, we will not include those values when breaking down the data, but will include them when calculating the non-disaggregated totals. This sometimes leads to very long and unwieldy footnotes. 

For example, see the following footnote in the Pennsylvania dashboard that, when expanded, takes up a significant amount of the screen space without providing much useful/actionable information. 

### Proposed Solution
- Put the unknown values in the CSV upon download, but don’t display them in the footnote. This is important 
- Instead, just say in the footnote: “This data includes some individuals for whom age, gender, or race/ethnicity is not reported. These individuals count toward the total but are excluded from demographic breakdown views, counting towards a maximum difference of X% between the total and the sum of broken down figures. For more information, **download the data** and view the README.txt." 
    - ‘download the data’ should trigger the download function for that visualization. 
- The README should contain the more detailed information in a “VISUALIZATION FOOTNOTES” section, where all future footnotes should be included.

### PR DESCRIPTION
**Pull request by terryttsai**
## Description of the change

Remove unknown data from footnote and add to the README when downloading datasets

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #514

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts [hunk 1]
```diff
@@ -196,4 +199,44 @@ export default class HistoricalPopulationBreakdownMetric extends Metric<Historic
...
+
+        label = format(entry.date, "MMM d y");
+
+        return `${formattedCounts} for ${label}`;
+      })
+      .join("; ");
+
+    return (
+      this.methodology +
+      `\n\nVISUALIZATION FOOTNOTES\n\n
```
Comment (terryttsai) [inline spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts:234]: in `downloadData` we have this step where we take the readme and strip out newlines and replace them with spaces. I'm thinking we should format our readme so we don't have to do that, so we can have newlines in our readme?

File: spotlight-client/src/VizNotes/UnknownsNote.tsx [hunk 2]
```diff
@@ -101,16 +102,21 @@ function useFormattedUnknowns(unknowns: Unknowns) {
...
   return (
     <AutoHeightTransition>
       This data includes some individuals for whom age, gender, or
       race/ethnicity is not reported. These individuals count toward the total
-      but are excluded from demographic breakdown views. Unknown values
-      comprise: {useFormattedUnknowns(unknowns)}.
+      but are excluded from demographic breakdown views, counting towards a
+      maximum difference of X% between the total and the sum of broken down
+      figures. For more information,{" "}
+      <Link to="" onClick={download}>
```
[the remark this answers is not in the document]
Comment (macfarlandian) [reply spotlight-client/src/VizNotes/UnknownsNote.tsx:116]: you don't need a router link component here at all, instead this should just be a `Button`. You can use the design system "link" style to make it look less button-y

File: spotlight-client/src/VizNotes/VizNotes.tsx [hunk 3]
```diff
@@ -25,14 +25,19 @@ import { UnknownsNote } from "./UnknownsNote";
 type VizNotesProps = {
   smallData?: boolean;
   unknowns?: Unknowns;
+  download?: () => Promise<void>;
```
Comment (macfarlandian) [inline spotlight-client/src/VizNotes/VizNotes.tsx:28]: does this prop actually need to be optional?

File: spotlight-client/src/VizNotes/UnknownsNote.tsx [hunk 4]
```diff
@@ -101,16 +102,21 @@ function useFormattedUnknowns(unknowns: Unknowns) {
...
-export const UnknownsNote = ({ unknowns }: UnknownsNoteProps): JSX.Element => {
+export const UnknownsNote = ({ download }: UnknownsNoteProps): JSX.Element => {
   return (
     <AutoHeightTransition>
       This data includes some individuals for whom age, gender, or
       race/ethnicity is not reported. These individuals count toward the total
-      but are excluded from demographic breakdown views. Unknown values
-      comprise: {useFormattedUnknowns(unknowns)}.
+      but are excluded from demographic breakdown views, counting towards a
+      maximum difference of X% between the total and the sum of broken down
```
Comment (macfarlandian) [inline spotlight-client/src/VizNotes/UnknownsNote.tsx:114]: should "X" be a real number here that is derived from the data?

File: spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts [hunk 5]
```diff
@@ -196,4 +199,44 @@ export default class HistoricalPopulationBreakdownMetric extends Metric<Historic
 
     return countsByDate.length ? countsByDate : undefined;
   }
+
+  get readme(): string {
```
[the remark this answers is not in the document]
Comment (macfarlandian) [reply spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts:203]: the formatting logic previously used by the UI is already generic for different types of unknowns; you ought to be able to port all of that into this function. Then it will no longer be specific to this metric type and you can lift it up to the Metric superclass

File: spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts (hunk 1 above)
Comment (macfarlandian) [reply spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts:234]: I agree this seems like the right place to do that preprocessing, if you can figure out a good solution!

File: spotlight-client/src/contentModels/SupervisionSuccessRateMetric.ts [hunk 6]
```diff
@@ -240,7 +240,7 @@ export default class SupervisionSuccessRateMetric extends Metric<SupervisionSucc
    * Creates a zip file of all this metric's data in CSV format and
    * initiates a download of that file in the user's browser.
    */
-  async download(): Promise<void> {
+  download = async (): Promise<void> => {
```
Comment (macfarlandian) [inline spotlight-client/src/contentModels/SupervisionSuccessRateMetric.ts:243]: clever, I didn't know you could do this

File: spotlight-client/src/VizNotes/UnknownsNote.tsx (hunk 4 above)
Comment (terryttsai) [reply spotlight-client/src/VizNotes/UnknownsNote.tsx:32]: Dunno, I was just following the issue!

File: spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (terryttsai) [reply spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts]: Now the Metric superclass should handle generating the readme

File: spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts (hunk 1 above)
Comment (terryttsai) [reply spotlight-client/src/contentModels/HistoricalPopulationBreakdownMetric.ts]: I strip away the newlines in the `methodology` but preserve newlines in my visualization footnotes.

File: spotlight-client/src/VizNotes/VizNotes.tsx (hunk 3 above)
Comment (terryttsai) [reply spotlight-client/src/VizNotes/VizNotes.tsx]: We do use VizNotes without `unknowns` which means also no need for `download`

**Comment by terryttsai** [comment]
Updated the PR to address PR comments, anyone to check off the new README contents and footnote copy with?

**Comment by macfarlandian** [comment]
yes you should run it by @hobuobi who can also answer the "X%" question

File: spotlight-client/src/VizNotes/UnknownsNote.tsx (hunk 4 above)
Comment (hobuobi) [reply spotlight-client/src/VizNotes/UnknownsNote.tsx:32]: Ideally this would be derived from the data itself, but I think we can use an alternative that doesn't require that! How about this instead (simply removes the relevant phrase): 
> This data includes some individuals for whom age, gender, or race/ethnicity is not reported. These individuals count toward the total but are excluded from demographic breakdown views. For more details, download the data and view the README.txt.

Comment (terryttsai) [reply spotlight-client/src/VizNotes/UnknownsNote.tsx:32]: So just to confirm, this footnote applies to every single metric that could possibly have unknowns in the spotlight app?

File: spotlight-client/src/contentModels/Metric.ts [hunk 7]
```diff
@@ -194,24 +220,59 @@ export default abstract class Metric<RecordFormat extends MetricRecord>
     return this.allRecords;
   }
 
+  get unknowns(): Unknowns | undefined {
+    return undefined;
+  }
```
Comment (macfarlandian) [inline spotlight-client/src/contentModels/Metric.ts:225]: I believe this needs be added to the `makeObservable` call in the constructor?

File: spotlight-client/src/contentModels/Metric.ts [hunk 8]
```diff
@@ -194,24 +220,59 @@ export default abstract class Metric<RecordFormat extends MetricRecord>
...
+
+  generateReadme(): string {
```
Comment (macfarlandian) [inline spotlight-client/src/contentModels/Metric.ts:227]: I think this should probably be a computed getter instead ... this happens to work fine at the moment because we only call it within the download method, but if we wanted to put this text somewhere in the UI again later it won't be properly observable

File: spotlight-client/src/contentModels/Metric.ts (hunk 7 above)
Comment (terryttsai) [reply spotlight-client/src/contentModels/Metric.ts:227]: Good catch, fixed!

File: spotlight-client/src/contentModels/Metric.ts (hunk 8 above)
Comment (terryttsai) [reply spotlight-client/src/contentModels/Metric.ts]: Sounds good to me, also if we re-download the data for some reason it'll just be computed once

Comment (macfarlandian) [reply spotlight-client/src/contentModels/Metric.ts]: that may not be completely true since the download function is not really a reactive context, but it's also not any worse than it was previously

**Review by macfarlandian — APPROVED** [review]
other than the CI failures LGTM!
