### PR TITLE
Stacked Bar Charts for Demographic Population Breakdowns

### LINKED ISSUE #11: [Parole page] Stacked bar charts for demographic population breakdowns
Input:
- Aggregate population broken down by district, race, gender, age bracket (from server)
- Selected district as filter

Output:
- total population (after filtering) as number
- three single stacked bars, one each for race, gender, age bracket (broken down as percentage) (use component from #15)

### PR DESCRIPTION
**Pull request by sprad**
## Description of the change

- Adding a stacked bar chart to break down parole demographic information such as gender, age, and race.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #11

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

File: src/constants.js [hunk 1]
```diff
@@ -18,7 +18,13 @@ export const DIMENSION_KEYS = {
   total: "total",
 };
 
-const DIMENSIONS = {
+export const DATA_KEY_TRANSLATIONS = {
+  [DIMENSION_KEYS.gender]: "gender",
+  [DIMENSION_KEYS.age]: "age_bucket",
+  [DIMENSION_KEYS.race]: "race_or_ethnicity",
+};
```
Comment (sprad) [inline src/constants.js:25]: The keys in the provided data are a bit different than the ones we work with internally so this mapping provides a "translation" between the two worlds.

File: src/viz-parole-population/VizParolePopulation.js [hunk 2]
```diff
@@ -21,6 +46,100 @@ const MapCaption = styled.figcaption`
...
+function VizParaoleDistrictCount({ data, currentDistrict }) {
+  if (!currentDistrict) return null;
+
+  const districtData = data[currentDistrict];
+
+  // Each individual district has an "aggregate record" which is defined
+  // by each of its demographic entries being set to "ALL".  Unfortunately,
+  // when no district is selected, there is no "aggregate record" so to get
+  // the population total, we sum the total of the population across a
+  // single dimension, in this case GENDER.
```
Comment (sprad) [inline src/viz-parole-population/VizParolePopulation.js:67]: Ideally, the record that represents the entire state (i.e. the "ALL" district) would also have an "aggregate record", but it does not.  Is this something we can fix upstream so that we can avoid this hack?

**Comment by sprad** [comment]
So there's not much code here and 90% of the work was finished relatively quickly.  The remaining 10% however has been dragging and still isn't quite there.  Getting the data whipped into shape and sending it to the charting library for display was straightforward:

Screen Shot 2020-07-13 at 9 13 53 AM

I'm still struggling a bit to understand how to structure the code and components in such that they're generic, but also so that they work within a specific context.  More specifically, I'm trying to get everything to match up as closely as possible to the provided mocks without doing too much surgery to the underlying chart primitive components (i.e. `ProportionalBar` in this case).

This is causing a handful of issues. For example, to get the bar charts to look like the mocks, I actually created 3 separate bar charts within a loop.  On their own, the charts look fine but things like the tooltips are breaking because they're getting hidden behind the other bar charts as follows:

Screen Shot 2020-07-13 at 9 14 11 AM

I've played with `z-index` for everything to no avail, so I'll just need to keep messing around with things until I figure it out.

At any rate, I wanted to get this PR up so that it's available.  I'll get the remaining polish added on Wednesday.

File: src/proportional-bar/ProportionalBar.js [hunk 3]
```diff
@@ -122,4 +122,9 @@ ProportionalBar.propTypes = {
     })
   ).isRequired,
   title: PropTypes.string.isRequired,
+  showLegend: PropTypes.bool,
+};
+
+ProportionalBar.defaultProps = {
+  showLegend: false,
```
Comment (macfarlandian) [inline src/proportional-bar/ProportionalBar.js:129]: I would default this to `true`, we should only be hiding it in special cases

File: src/viz-parole-population/VizParolePopulation.js [hunk 4]
```diff
@@ -21,6 +46,100 @@ const MapCaption = styled.figcaption`
...
+const ParoleDemographicsWrapper = styled.figure`
+  height: 64px;
+  width: 376px;
+`;
+
+const ParoleDistrictCountWrapper = styled.div`
+  text-align: right;
+`;
+
+function VizParaoleDistrictCount({ data, currentDistrict }) {
```
Comment (macfarlandian) [inline src/viz-parole-population/VizParolePopulation.js:58]: Nit: `Parole`

File: src/viz-parole-population/VizParolePopulation.js (hunk 2 above)
Comment (macfarlandian) [reply src/viz-parole-population/VizParolePopulation.js:67]: that would be a question for @jjdressel11

File: src/viz-parole-population/VizParolePopulation.js [hunk 5]
```diff
@@ -21,6 +46,100 @@ const MapCaption = styled.figcaption`
...
+          label,
+          value: +record.total_supervision_count,
+        }))
+        .shift();
+    })
+    .filter((record) => record);
+
+  return (
+    <ParoleDemographicsWrapper>
+      <ProportionalBar data={dimensionData} title={DIMENSIONS[dimension.key]} />
```
Comment (macfarlandian) [inline src/viz-parole-population/VizParolePopulation.js:125]: i think we should be including the legends here?

File: src/constants.js [hunk 6]
```diff
@@ -18,7 +18,13 @@ export const DIMENSION_KEYS = {
   total: "total",
 };
 
-const DIMENSIONS = {
+export const DATA_KEY_TRANSLATIONS = {
```
Comment (macfarlandian) [inline src/constants.js:21]: i have a renaming suggestion for this: `DIMENSION_DATA_KEYS` ... I think it's good to be a little more specific about what kind of keys we are describing here

File: src/constants.js [hunk 7]
```diff
@@ -18,7 +18,13 @@ export const DIMENSION_KEYS = {
...
+  [DIMENSION_KEYS.gender]: "gender",
+  [DIMENSION_KEYS.age]: "age_bucket",
+  [DIMENSION_KEYS.race]: "race_or_ethnicity",
+};
+
+export const DIMENSIONS = {
```
Comment (macfarlandian) [inline src/constants.js:27]: similarly I would propose we rename this to `DIMENSION_LABELS`

File: src/constants.js [hunk 8]
```diff
@@ -34,6 +40,29 @@ export const DIMENSIONS_LIST = [
...
+};
+
+export const GENDERS = {
+  FEMALE: "Female",
+  MALE: "Male",
+};
+
+export const RACES = {
+  AMERICAN_INDIAN_ALASKAN_NATIVE: "American Indian or Alaskan Native",
+  ASIAN: "Asian",
```
Comment (jjdressel11) [inline src/constants.js:58]: Heads up that we aren't showing the "Asian" racial breakdown for the ND dashboard. We are grouping "Asian" with "Other" because of the small counts. This page seems to be a global constant file, so I'm sure that this will say here but wanted to flag this!

File: src/viz-parole-population/VizParolePopulation.js (hunk 2 above)
Comment (jjdressel11) [reply src/viz-parole-population/VizParolePopulation.js:67]: Yes! Just updated the query, and the files in GCS now have the district = ALL rows!

Let me know if there are any other places you are having to aggregate on the front end, because I can almost certainly send you those number pre-calculated.

File: src/viz-parole-population/VizParolePopulation.js (hunk 5 above)
Comment (sprad) [reply src/viz-parole-population/VizParolePopulation.js:125]: I was matching the mocks, which doesn't include the legends, but I agree that they should be included.  I'll need to do some work to get them added though because including them messes up the charts when the legend text wraps.  Example:

Screen Shot 2020-07-13 at 7 04 56 PM

File: src/constants.js (hunk 8 above)
Comment (sprad) [reply src/constants.js:58]: Thanks for the heads up, @jjdressel11.  I'm going to leave the constant here for now so that it's available for other states in the future.  Appreciate the flag!

File: src/viz-parole-population/VizParolePopulation.js (hunk 2 above)
Comment (sprad) [reply src/viz-parole-population/VizParolePopulation.js:67]: Awesome!  Thanks @jjdressel11.  Just to be clear, that means there's now a record in the file that looks something like this, right?

```json
  {
    "state_code": "US_ND",
    "total_supervision_count": "934",
    "supervision_type": "PAROLE",
    "district": "ALL",
    "race_or_ethnicity": "ALL",
    "gender": "ALL",
    "age_bucket": "ALL"
  },
```

Notice that all of the dimension keys (i.e. `race_or_ethnicity`, `gender`, and `age_bucket`) are all set to `ALL` for the `ALL district` record.

**Comment by sprad** [comment]
@macfarlandian - I'd probably not block #30 on this review.  It's still got a handful of things that need to be updated before it's ready to merge and I'll be in and out as time permits until I'm back on the Recidiviz clock on Wednesday.  Feel free to merge #30 whenever and I'll handle any merge conflicts on my end.

**Comment by macfarlandian** [comment]
@sprad right yeah ... I think what I will actually do is incorporate your expanded constants into this branch in such a way that hopefully doesn't cause too much of a merge nightmare for you on wednesday

File: src/viz-parole-population/VizParolePopulation.js (hunk 2 above)
Comment (jjdressel11) [reply src/viz-parole-population/VizParolePopulation.js:67]: Yes, here's the exact record (with staging data):

```
{"state_code":"US_ND","supervision_type":"PAROLE","district":"ALL","race_or_ethnicity":"ALL","gender":"ALL","age_bucket":"ALL","total_supervision_count":"934"}
```

Comment (sprad) [reply src/viz-parole-population/VizParolePopulation.js:67]: Boom!  That's perfect.  Thanks, @jjdressel11!

File: src/viz-parole-population/VizParolePopulation.js (hunk 5 above)
Comment (macfarlandian) [reply src/viz-parole-population/VizParolePopulation.js]: yeah I noticed that ... I didn't really anticipate this when I created that chart component unfortunately ... looks like not-fun to fix! 😎

File: src/assets/test_data/US_ND_parole_population_by_district_by_demographics.json [hunk 9]
```diff
@@ -1825,5 +1825,14 @@
...
     "age_bucket": "ALL"
+  },
+  {
+    "state_code": "US_ND",
+    "supervision_type": "PAROLE",
+    "district": "ALL",
+    "race_or_ethnicity": "ALL",
+    "gender": "ALL",
+    "age_bucket": "ALL",
+    "total_supervision_count": "4235"
```
Comment (sprad) [inline src/assets/test_data/US_ND_parole_population_by_district_by_demographics.json:1836]: I'm not entirely sure where these files or kept or if I have access to them so I just added this total record for the "ALL" district manually.  We can nuke it if there's an updated file to replace it with.

File: src/constants.js [hunk 10]
```diff
@@ -81,30 +79,30 @@ export const AGE_KEYS = {
   over40: "40<",
 };
 
-export const AGES = {
-  [AGE_KEYS.under25]: "<25",
-  [AGE_KEYS["25_29"]]: "25-29",
-  [AGE_KEYS["30_34"]]: "30-34",
-  [AGE_KEYS["35_39"]]: "35-39",
-  [AGE_KEYS.over40]: "40<",
+const AGES = new Map([
```
Comment (sprad) [inline src/constants.js:82]: I made all of these demographic collections `Maps` to preserve insertion order similar to the `DIMENSION_MAPPINGS`

File: src/viz-parole-population/VizParolePopulation.js [hunk 11]
```diff
@@ -1,26 +1,129 @@
...
 
 const VizParolePopulationContainer = styled.div`
   display: flex;
   flex-wrap: wrap;
   justify-content: space-between;
 `;
+
 const VizWrapper = styled.div`
-  flex: 0 1 auto;
+  flex: 0 1 49%;
```
Comment (sprad) [inline src/viz-parole-population/VizParolePopulation.js:34]: This section of the page is perhaps slightly unique in that it has multiple visualizations (the Map and the Statistic Number/Bar Charts).  I wanted to give equal width sizings (i.e. 50%) to each of these visualization sections, but when I did the visualization section on the right side wrapped.

File: src/assets/test_data/US_ND_parole_population_by_district_by_demographics.json (hunk 9 above)
Comment (macfarlandian) [reply src/assets/test_data/US_ND_parole_population_by_district_by_demographics.json:1836]: oh right I can send you this

**Comment by sprad** [comment]
Sorry for the glacial pace on getting this squared away.  I've mostly been wrestling with and sinking a ton of time into figuring how all of the layout stuff should be put together so that things look decent on smaller screens.  I think I've got things in a reasonable spot at this point.

That said, I'm still circling the drain on figuring out what to do when there are so many labels in the color legend that the text wraps and it throws off the proportions of the overall bar chart.

Screen Shot 2020-07-15 at 3 17 41 PM

File: src/viz-parole-population/VizParolePopulation.js (hunk 11 above)
Comment (macfarlandian) [reply src/viz-parole-population/VizParolePopulation.js:34]: this seems fine to me ... i am doing another pass at the responsive layout for this section so if there is any new weirdness that crops up from that I will deal with it

File: src/viz-parole-population/VizParolePopulation.js [hunk 12]
```diff
@@ -1,26 +1,128 @@
...
+    </ParaoleDemographicsDistrictCountWrapper>
+  );
+}
+
+ParaoleDemographicsDistrictCount.propTypes = {
+  data: PropTypes.arrayOf(PropTypes.object),
+};
+
+ParaoleDemographicsDistrictCount.defaultProps = {
+  data: undefined,
```
Comment (macfarlandian) [inline src/viz-parole-population/VizParolePopulation.js:85]: sp: `Parole` 🤓

File: src/viz-parole-population/VizParolePopulation.js [hunk 13]
```diff
@@ -1,26 +1,128 @@
...
+
 const MapCaption = styled.figcaption`
   color: ${(props) => props.theme.colors.body};
   font: ${(props) => props.theme.fonts.body};
 `;
 
+const ParoleDemographicsWrapper = styled.div`
+  height: 100%;
+  margin: 0;
+  padding-left: 56px;
```
Comment (sprad) [inline src/viz-parole-population/VizParolePopulation.js:49]: One thing in particular that I'm not quite grasping in regards to how to get things looking good on smaller devices is how we'll handle styles that are needed when two side by side elements are in a non-wrapped context (i.e. on a Desktop), but then transition to a wrapped context (mobile) where the styles are no longer needed.

The specific example here is that we need some space between the state map and the demographic bar charts when they're side by side, but that space is no longer needed once the screen size is reduced and the bar charts wrap below the map.

File: src/viz-parole-population/VizParolePopulation.js (hunk 12 above)
Comment (sprad) [reply src/viz-parole-population/VizParolePopulation.js]: And it's only Wednesday...
