### PR TITLE
Prison Page: Population Section

### LINKED ISSUE #46: [Prison page] Population overview
The visualizations in this section are identical to the population section of the Parole page; but rather than districts the population is divided up by facilities. See mocks for more detail

### LINKED ISSUE #48: [Sentencing page] Sentencing population section
The visualizations for this section is similar to the population sections on other pages; the map should depict Judicial District instead of counties (we will have to generate a new topography file for them from our ND map assets). See mock for more details.

### LINKED ISSUE #81: Gracefully handle errors from clicking on districts that have no data points
On the Probation page, in staging, the Northwest jurisdiction has no data points in the _Who is on probation_ chart. Clicking on that region on the map, or selecting Northwest in the dropdown, causes the page to break. See the screenshots below:

District:
Screen Shot 2020-07-28 at 22 22 34

Error:
Screen Shot 2020-07-28 at 22 19 42

### PR DESCRIPTION
**Pull request by sprad**
## Description of the change

Adding the population section to the prison page.  **Note:**  The `incarceration_population_by_facility_by_demographics.json` has been randomized.

This map looks a bit odd because many of the facilities are clustered together and overlap with one another.  This makes it difficult, if not impossible, to click the facilities on the map.

Screen Shot 2020-07-24 at 6 17 29 PM

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #46
> Closes #48 
> Closes #81 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by sprad** [comment]
This PR is complete in the sense that the Population Section shows up as expected on the Prison page.  Unfortunately, I have to step out for a dinner reservation and there a few code clean up things that I'd still like to address:

- Renaming `StateOfficeMap` to `StateCountyMap` to reflect the true nature of what the topography shows and so that it fits in nicer within the `VizPrizonPopulation` component which does show the map by county, but populates it with "facilities" not "offices".
- Refactor `VizParolePopulation` and `VizPrizonPopulation` since they are almost identical.

I wanted to get this PR up now in case there was any urgency or desire to get this deployed to staging in the near future.  I'll assign myself to work on the [Population Section on the Sentencing Page](https://github.com/Recidiviz/public-dashboard/issues/48) next which I'm assuming will further exacerbate the need for the proposed refactorings.

**Comment by sprad** [comment]
Alright, I've added three commits to this PR.  Sorry for the mess and all of the code and file churn.  In aggregate, this PR is probably a bit overwhelming and difficult to grasp, but each individual commit builds upon the previous and in isolation should be pretty straightforward.  I'd recommend reading and commenting on each commit separately.  Here's a description of each commit to help guide you along:

[New Commit 1.  Sentencing Page: Population Section](https://github.com/Recidiviz/public-dashboard/pull/71/commits/5799c8bf84a0ccf6c92748344df0a26038330726)

This commit completes the work for [Issue #48](https://github.com/Recidiviz/public-dashboard/issues/48).  I've included it here because it allows the next two refactoring commits to be completed in whole.

[New Commit 2.  Population Component Duplication Refactor](https://github.com/Recidiviz/public-dashboard/pull/71/commits/6157461d056572263886b3caa33d9d5bfc2a780e)

This commit cleans up all of the duplication and naming issues in the `Viz*Population` components.  Essentially, these components end up reducing down to wrappers around the `PopulationViz` component but are themselves responsible for gathering and shaping the relevant population data, defining visualization labels, and selecting a map type to display.

[New Commit 3.  Map Component Refactor](https://github.com/Recidiviz/public-dashboard/pull/71/commits/c6c7c01cb6845ed3b77001bb35379cdab500f607)

This commit is perhaps a bit controversial and if we don't like it, it's easy enough to revert on its own.  The gist is that while I've been working with these map components I've made the observation that our map visualizations are a combination of two things:  1). A topology and 2). An interaction style.

We currently have three map topologies:

1. State Counties
2. State Judicial Districts
3. State Program Regions

And we currently have two interaction styles:

1. Maps with clickable markers
2. Maps with clickable regions

This commit teases the interaction styles out of and away from the topologies such that they themselves become their own generic map component primitives.  This should allow us to reuse these components in the future without worry about getting them awkwardly tied up with a specific topology.


Assuming no issues are discovered and any feedback is incorporated, these commits are meant to be mergeable at this point.  The issue with the overlapping markers still exists, but I've opened a [separate issue](https://github.com/Recidiviz/public-dashboard/issues/73) to figure out the desired UI and resolution to that problem.

File: src/page-sentencing/PageSentencing.js [hunk 1]
```diff
@@ -4,20 +4,44 @@ import useChartData from "../hooks/useChartData";
...
+      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit.
+      Vestibulum in finibus tellus, et ullamcorper augue. Quisque eleifend
+      tortor vitae iaculis egestas. Donec dictum, nunc nec tincidunt cursus,
+      ipsum dui gravida.`,
+      showLocationControl: true,
+      locationControlLabel: "Judicial District",
+      VizComponent: VizSentencePopulation,
+      vizData: {
+        populationDemographics: sentenceTypeByDistrictByDemographics,
+        locations: apiData.judicial_districts.filter(districtIsPopulated),
```
Comment (sprad) [inline src/page-sentencing/PageSentencing.js:41]: The `apiData.judicial_districts` call returns a district called "[Other](https://github.com/Recidiviz/public-dashboard/blob/master/server/core/demo_data/judicial_districts.json#L9)" such that it is displayed in the location dropdown control.  However, the `apiData.sentence_type_by_district_by_demographics` doesn't return any records with a district mapped to "Other".  The effect is that when the "Other" option is selected from the location control, an error is thrown and the page blows up.  To get around this issue, I filter the `apiData.judicial_districts` down to only include districts that are found within the data returned by `apiData.sentence_type_by_district_by_demographics`.

File: src/page-sentencing/PageSentencing.js [hunk 2]
```diff
@@ -4,20 +4,44 @@ import useChartData from "../hooks/useChartData";
...
+      title: "Who is being sentenced?",
+      description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit.
+      Vestibulum in finibus tellus, et ullamcorper augue. Quisque eleifend
+      tortor vitae iaculis egestas. Donec dictum, nunc nec tincidunt cursus,
+      ipsum dui gravida.`,
+      showLocationControl: true,
+      locationControlLabel: "Judicial District",
+      VizComponent: VizSentencePopulation,
+      vizData: {
+        populationDemographics: sentenceTypeByDistrictByDemographics,
```
Comment (sprad) [inline src/page-sentencing/PageSentencing.js:40]: I don't have access to a separate sentencing population file, but from what I can tell the data returned from `apiData.sentence_type_by_district_by_demographics` should be reusable for this use case.

File: src/viz-sentence-population/VizSentencePopulation.js [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+      MapComponent={SentenceMap}
+      mapComponentProps={{
+        data: judicialDistrictTotals,
+        currentLocation: locationId,
+        onLocationClick,
+      }}
+      mapLabel="Judicial districts in North Dakota"
+      locationAccessorFn={(record) => record.district}
+      populationAccessorFn={(record) =>
+        Number(record.incarceration_count) + Number(record.probation_count)
```
Comment (sprad) [inline src/viz-sentence-population/VizSentencePopulation.js]: I add the `incarceration_count` and `probation_count` such that the total number of sentences are displayed in this component.  I know we talked about adding a new control to allow users to filter based on sentence type, but that is a problem for another day.

File: src/page-sentencing/PageSentencing.js [hunk 4]
```diff
@@ -4,20 +4,44 @@ import useChartData from "../hooks/useChartData";
 import VizSentenceTypes from "../viz-sentence-types";
 import VizSentenceLengths from "../viz-sentence-lengths";
 
+import VizSentencePopulation from "../viz-sentence-population";
```
Comment (sprad) [inline src/page-sentencing/PageSentencing.js:7]: Self nit: extra line above this import

File: src/viz-sentence-population/VizSentencePopulation.js [hunk 5]
```diff
@@ -0,0 +1,175 @@
+import PropTypes from "prop-types";
```
Comment (sprad) [inline src/viz-sentence-population/VizSentencePopulation.js]: FYI, all of the duplication in this file disappears in the [next commit](https://github.com/Recidiviz/public-dashboard/pull/71/commits/6157461d056572263886b3caa33d9d5bfc2a780e)

File: src/state-judicial-district-map/StateJudicialDistrictMap.js [hunk 6]
```diff
@@ -0,0 +1,113 @@
+import PropTypes from "prop-types";
```
Comment (sprad) [inline src/state-judicial-district-map/StateJudicialDistrictMap.js:1]: All of this State Judicial District Map code was duplicated verbatim in `VizParolePopulation` and `VizSentencePopulation`.  It now lives in one place here.

File: src/viz-parole-population/VizParolePopulation.js [hunk 7]
```diff
@@ -1,64 +1,39 @@
...
+        ),
+        currentLocation: locationId,
+        onLocationClick,
       }}
-      mapLabel="Parole offices in North Dakota"
-      locationAccessorFn={(record) => record.district}
-      populationAccessorFn={(record) => Number(record.total_supervision_count)}
+      mapLabel="Parole locations in North Dakota"
+      locationAccessorFn={locationAccessorFn}
+      populationAccessorFn={populationAccessorFn}
```
Comment (sprad) [inline src/viz-parole-population/VizParolePopulation.js:33]: Each of these `Viz*Population` components now basically boils down to a wrapper around `PopulationViz` that:

1.  Specifies a MapComponent (i.e. `StateCountyMap`)
2.  Defines which data to pass along (i.e. `locationTotals`) and how to access its properties (i.e. `locationAccessorFn` and `populationAccessorFn`).
3.  Provides context-specific labels (i.e. "Parole locations in North Dakota", etc.)

File: src/clickable-marker-map/ClickableMarkerMap.js [hunk 8]
```diff
@@ -0,0 +1,137 @@
...
+  &:hover {
+    fill: ${(props) => props.theme.mapMarkers.hover.fill};
+  }
+
+  &:active {
+    fill: ${(props) => props.theme.mapMarkers.pressed.fill};
+  }
+`;
+
+export default function ClickableMarkerMap({
```
Comment (sprad) [inline src/clickable-marker-map/ClickableMarkerMap.js:37]: This is the map that underlies the Prison Population and Parole Population maps.  I don't really care for the names `ClickableMarkerMap` and `ClickableRegionMap`, but they are if nothing else, quite literal.  If we don't like the idea of extracting these components based upon their interaction style, then you can stop reading here and we can revert this commit.

File: src/page-sentencing/PageSentencing.js (hunk 1 above)
Comment (jessex) [reply src/page-sentencing/PageSentencing.js:41]: @macfarlandian I can imagine cases where this would _not_ be the ideal behavior. For example, in cases where some particular breakdown by time and demographic leads to a 0 for a particular district, would we want to display some nominal pointer to that district instead of just relying on its absence for communication?

File: src/viz-parole-population/VizParolePopulation.js [hunk 9]
```diff
@@ -1,64 +1,39 @@
...
+          populationAccessorFn,
+          locationAccessorFn
+        ),
+        currentLocation: locationId,
+        onLocationClick,
       }}
-      mapLabel="Parole offices in North Dakota"
-      locationAccessorFn={(record) => record.district}
-      populationAccessorFn={(record) => Number(record.total_supervision_count)}
+      mapLabel="Parole locations in North Dakota"
```
Comment (jessex) [inline src/viz-parole-population/VizParolePopulation.js:31]: Do we actually want this copy change, or is it an over eager find+replace?

Comment (sprad) [reply src/viz-parole-population/VizParolePopulation.js:31]: Overeager find/replace.  Good eyes 👀

File: src/page-sentencing/PageSentencing.js (hunk 1 above)
Comment (macfarlandian) [reply src/page-sentencing/PageSentencing.js:41]: yeah, unfortunately rows that zero out are simply dropped from the data file, so we can't rely on file contents to be exhaustive; `judicial_districts` is the source of truth. If there is a missing district we should plug that gap with zeroes or "no data" states as required.

File: src/clickable-marker-map/ClickableMarkerMap.js (hunk 8 above)
Comment (macfarlandian) [reply src/clickable-marker-map/ClickableMarkerMap.js:37]: it's not a problem for now but I am worried that this division may prove too prescriptive, i.e. if we have a need for a map that combines both interaction styles. My thought on this had been to extend `StateMap` to also support clickable markers, since I don't think there is really any reason they need to be mutually exclusive. (It's possible that wouldn't have worked well in practice? I didn't take it farther than a vague idea.)

**Comment by sprad** [comment]
I reverted the map refactoring commit and have handled the situation where we don't have any data for a district in this [latest commit](https://github.com/Recidiviz/public-dashboard/pull/71/commits/36468766a9597e2c8c1c0d1d2ff4e0f1471d1e4d).  The output for districts with missing data now looks like this:

Screen Shot 2020-07-29 at 10 18 24 AM

**Comment by sprad** [comment]
@jessex The latest commit should also resolve the issue for #81

**Comment by jessex** [comment]
Fantastic, thanks for that @sprad!
